# Generated by Django 5.2.15 on 2026-06-16 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_coroinha_foto_inscricao_foto_pendente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoParoquial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricoes_abertas', models.BooleanField(default=False)),
                ('inscricoes_atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricoes_atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_inscricoes_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração paroquial',
                'verbose_name_plural': 'Configurações paroquiais',
            },
        ),
    ]
