# Generated by Django 5.2.15 on 2026-07-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_configuracao_paroquial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('cpf', models.CharField(db_index=True, max_length=11)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('senha_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], db_index=True, default='Pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('coroinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_acesso', to='membership.coroinha')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_acesso_processadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de acesso',
                'verbose_name_plural': 'Solicitações de acesso',
                'ordering': ['-criado_em'],
            },
        ),
    ]
