# Generated by Django 5.2.15 on 2026-07-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_escala_mensal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missa',
            options={'ordering': ['dia_mes', 'dia_semana', 'horario'], 'verbose_name': 'Missa', 'verbose_name_plural': 'Missas'},
        ),
    ]
