# Generated by Django 5.2.15 on 2026-07-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('login_sucesso', 'Login bem-sucedido'), ('login_falha', 'Tentativa de login falhou'), ('recuperar_senha', 'Recuperação de senha'), ('recuperar_senha_falha', 'Recuperação de senha falhou'), ('presenca_registrada', 'Presença registrada'), ('inscricao_criada', 'Inscrição pública criada'), ('inscricao_aprovada', 'Inscrição aprovada'), ('inscricao_rejeitada', 'Inscrição rejeitada'), ('solic_acesso_criada', 'Solicitação de acesso criada'), ('solic_acesso_aprovada', 'Solicitação de acesso aprovada'), ('solic_acesso_rejeitada', 'Solicitação de acesso rejeitada'), ('mensagem_enviada', 'Mensagem enviada')], db_index=True, max_length=40),
        ),
    ]
